import React, { memo, useState } from 'react'
import { Text, View, StyleSheet } from 'react-native'
import { AutocompleteDropdown } from 'react-native-autocomplete-dropdown'
import colors from '../config/colors';

export const SearchComp = memo(() => {
  const [selectedItem, setSelectedItem] = useState(null)

  return (
    <View>
      <AutocompleteDropdown style={styles.container}
        clearOnFocus={false}
        closeOnBlur={true}
        textInputProps={{
          placeholder: 'Type a Player',
        }}
        onSelectItem={setSelectedItem}
        dataSet={[
                { id: "1", title: "Precious Achiuwa" },
                { id: "2", title: "Jaylen Adams" },
                { id: "3", title: "Steven Adams" },
                { id: "4", title: "Bam Adebayo" },
                { id: "5", title: "LaMarcus Aldridge" },
                { id: "6", title: "Ty-Shon Alexander" },
                { id: "7", title: "Nickeil Alexander-Walker" },
                { id: "8", title: "Grayson Allen" },
                { id: "9", title: "Jarrett Allen" },
                { id: "10", title: "Kadeem Allen" },
                { id: "11", title: "Al-Farouq Aminu" },
                { id: "12", title: "Kyle Anderson" },
                { id: "13", title: "Giannis Antetokounmpo" },
                { id: "14", title: "Kostas Antetokounmpo" },
                { id: "15", title: "Thanasis Antetokounmpo" },
                { id: "16", title: "Carmelo Anthony" },
                { id: "17", title: "Cole Anthony" },
                { id: "18", title: "OG Anunoby" },
                { id: "19", title: "Ryan Arcidiacono" },
                { id: "20", title: "Trevor Ariza" },
                { id: "21", title: "D.J. Augustin" },
                { id: "22", title: "Deni Avdija" },
                { id: "23", title: "Deandre Ayton" },
                { id: "24", title: "Udoka Azubuike" },
                { id: "25", title: "Dwayne Bacon" },
                { id: "26", title: "Marvin Bagley III" },
                { id: "27", title: "LaMelo Ball" },
                { id: "28", title: "Lonzo Ball" },
                { id: "29", title: "Mo Bamba" },
                { id: "30", title: "Desmond Bane" },
                { id: "31", title: "Harrison Barnes" },  { id: "32", title: "RJ Barrett" },  { id: "33", title: "Will Barton" },  { id: "34", title: "Keita Bates-Diop" },  { id: "35", title: "Nicolas Batum" },  { id: "36", title: "Aron Baynes" },  { id: "37", title: "Kent Bazemore" },  { id: "38", title: "Darius Bazley" },  { id: "39", title: "Bradley Beal" },  { id: "40", title: "Malik Beasley" },  { id: "41", title: "Jordan Bell" },  { id: "42", title: "DeAndre' Bembry" },  { id: "43", title: "Davis Bertans" },  { id: "44", title: "Patrick Beverley" },  { id: "45", title: "Saddiq Bey" },  { id: "46", title: "Tyler Bey" },  { id: "47", title: "Khem Birch" },  { id: "48", title: "Goga Bitadze" },  { id: "49", title: "Bismack Biyombo" },  
                { id: "50", title: "Nemanja Bjelica" },
                { id: "51", title: "Eric Bledsoe" },
                { id: "52", title: "Bogdan Bogdanovic" },
                { id: "53", title: "Bojan Bogdanovic" },
                { id: "54", title: "Bol Bol" },
                { id: "55", title: "Marques Bolden" },
                { id: "56", title: "Jordan Bone" },
                { id: "57", title: "Isaac Bonga" },
                { id: "58", title: "Devin Booker" },
                { id: "59", title: "Chris Boucher" },
                { id: "60", title: "Brian Bowen II" },
                { id: "61", title: "Ky Bowman" },
                { id: "62", title: "Avery Bradley" },
                { id: "63", title: "Tony Bradley" },
                { id: "64", title: "Jarrell Brantley" },
                { id: "65", title: "Ignas Brazdeikis" },
                { id: "66", title: "Mikal Bridges" },
                { id: "67", title: "Miles Bridges" },
                { id: "68", title: "Moses Brown" },
                { id: "69", title: "Bruce Brown" },
                { id: "70", title: "Sterling Brown" },
                { id: "71", title: "Charlie Brown Jr." },
                { id: "72", title: "Troy Brown Jr." },
                { id: "73", title: "Jalen Brunson" },
                { id: "74", title: "Thomas Bryant" },
                { id: "75", title: "Reggie Bullock" },
                { id: "76", title: "Trey Burke" },
                { id: "77", title: "Alec Burks" },
                { id: "78", title: "Jimmy Butler" },
                { id: "79", title: "Bruno Caboclo" },
                { id: "80", title: "Devontae Cacok" },
                { id: "81", title: "Kentavious Caldwell-Pope" },
                { id: "82", title: "Facundo Campazzo" },
                { id: "83", title: "Vlatko Cancar" },
                { id: "84", title: "Clint Capela" },
                { id: "85", title: "Vernon Carey Jr." },
                { id: "86", title: "Jevon Carter" },
                { id: "87", title: "Wendell Carter Jr." },
                { id: "88", title: "Michael Carter-Williams" },
                { id: "89", title: "Alex Caruso" },
                { id: "90", title: "Willie Cauley-Stein" },
                { id: "91", title: "Chris Chiozza" },  { id: "92", title: "Marquese Chriss" },  { id: "93", title: "Gary Clark" },  { id: "94", title: "Brandon Clarke" },  { id: "95", title: "Jordan Clarkson" },  { id: "96", title: "Nicolas Claxton" },  { id: "97", title: "Amir Coffey" },  { id: "98", title: "John Collins" },  { id: "99", title: "Zach Collins" },  { id: "100", title: "Mike Conley" },
                { id: "101", title: "Pat Connaughton" },  { id: "102", title: "Quinn Cook" },  { id: "103", title: "Tyler Cook" },  { id: "104", title: "DeMarcus Cousins" },  { id: "105", title: "Robert Covington" },  { id: "106", title: "Allen Crabbe" },  { id: "107", title: "Torrey Craig" },  { id: "108", title: "Jamal Crawford" },  { id: "109", title: "Jae Crowder" },  { id: "110", title: "Seth Curry" },  { id: "111", title: "Stephen Curry" },  { id: "112", title: "Troy Daniels" },  { id: "113", title: "Anthony Davis" },  { id: "114", title: "Ed Davis" },  { id: "115", title: "Terence Davis" },  { id: "116", title: "DeMar DeRozan" },  { id: "117", title: "Dewayne Dedmon" },  { id: "118", title: "Sam Dekker" },  { id: "119", title: "Matthew Dellavedova" },  { id: "120", title: "Donte DiVincenzo" },  { id: "121", title: "Luka Doncic" },  { id: "122", title: "Hamidou Diallo" },  { id: "123", title: "Gorgui Dieng" },  { id: "124", title: "Spencer Dinwiddie" },  { id: "125", title: "Chris Douglas-Roberts" },  { id: "126", title: "PJ Dozier" },  { id: "127", title: "Luguentz Dort" },  { id: "128", title: "Luka Doncic" },  { id: "129", title: "Damian Dotson" },  { id: "130", title: "Kevin Durant" },  { id: "131", title: "Tyler Dorsey" },  { id: "132", title: "Toney Douglas" },  { id: "133", title: "Goran Dragic" },  { id: "134", title: "Jared Dudley" },  { id: "135", title: "Kris Dunn" },  { id: "136", title: "Kevin Durant" },  { id: "137", title: "Jacob Evans" },  { id: "138", title: "Dante Exum" },  { id: "139", title: "Cristiano Felicio" },  { id: "140", title: "Terrance Ferguson" },
                { id: "141", title: "Yogi Ferrell" },
                { id: "142", title: "Dorian Finney-Smith" },
                { id: "143", title: "Bryn Forbes" },
                { id: "144", title: "Evan Fournier" },
                { id: "145", title: "De'Aaron Fox" },
                { id: "146", title: "Melvin Frazier Jr." },
                { id: "147", title: "Markelle Fultz" },
                { id: "148", title: "Wenyen Gabriel" },
                { id: "149", title: "Daniel Gafford" },
                { id: "150", title: "Danilo Gallinari" },
                { id: "151", title: "Langston Galloway" },
                { id: "152", title: "Darius Garland" },
                { id: "153", title: "Marc Gasol" },
                { id: "154", title: "Rudy Gay" },
                { id: "155", title: "Paul George" },
                { id: "156", title: "Taj Gibson" },
                { id: "157", title: "Harry Giles III" },
                { id: "158", title: "Shai Gilgeous-Alexander" },
                { id: "159", title: "Rudy Gobert" },
                { id: "160", title: "Brandon Goodwin" },
                { id: "161", title: "Aaron Gordon" },
                { id: "162", title: "Eric Gordon" },
                { id: "163", title: "Devonte' Graham" },
                { id: "164", title: "Jerami Grant" },
                { id: "165", title: "Danny Green" },
                { id: "166", title: "Draymond Green" },
                { id: "167", title: "JaMychal Green" },
                { id: "168", title: "Javonte Green" },
                { id: "169", title: "Jeff Green" },
                { id: "170", title: "Josh Green" },
                { id: "171", title: "Blake Griffin" },
                { id: "172", title: "Eric Griffin" },
                { id: "173", title: "Kyle Guy" },
                { id: "174", title: "Rui Hachimura" },
                { id: "175", title: "Ashton Hagans" },
                { id: "176", title: "Tim Hardaway Jr." },
                { id: "177", title: "James Harden" },
                { id: "178", title: "Maurice Harkless" },
                { id: "179", title: "Jared Harper" },
                { id: "180", title: "Montrezl Harrell" },
                { id: "181", title: "Gary Harris" },
                { id: "182", title: "Joe Harris"},
                { id: "183", title: "Tobias Harris" },  { id: "184", title: "Jared Harper" },  { id: "185", title: "Josh Hart" },  { id: "186", title: "Isaiah Hartenstein" },  { id: "187", title: "Udonis Haslem" },  { id: "188", title: "Jaxson Hayes" },  { id: "189", title: "Killian Hayes" },  { id: "190", title: "Gordon Hayward" },  { id: "191", title: "Dewan Hernandez" },  { id: "192", title: "Juan Hernangomez" },  { id: "193", title: "Willy Hernangomez" },  { id: "194", title: "Tyler Herro" },  { id: "195", title: "Buddy Hield" },  { id: "196", title: "George Hill" },  { id: "197", title: "Solomon Hill" },  { id: "198", title: "Aaron Holiday" },  { id: "199", title: "Jrue Holiday" },  { id: "200", title: "Justin Holiday" },
                { id: "201", title: "Richaun Holmes" },
                { id: "202", title: "Rodney Hood" },
                { id: "203", title: "Al Horford" },
                { id: "204", title: "Danuel House Jr." },
                { id: "205", title: "Dwight Howard" },
                { id: "206", title: "Markus Howard" },
                { id: "207", title: "Kevin Huerter" },
                { id: "208", title: "Elijah Hughes" },
                { id: "209", title: "De'Andre Hunter" },
                { id: "210", title: "Chandler Hutchison" },
                { id: "211", title: "Serge Ibaka" },
                { id: "212", title: "Andre Iguodala" },
                { id: "213", title: "Ersan Ilyasova" },
                { id: "214", title: "Joe Ingles" },
                { id: "215", title: "Brandon Ingram" },
                { id: "216", title: "Kyrie Irving" },
                { id: "217", title: "Jonathan Isaac" },
                { id: "218", title: "Wes Iwundu" },
                { id: "219", title: "Frank Jackson" },
                { id: "220", title: "Jaren Jackson Jr." },
                { id: "221", title: "Josh Jackson" },
                { id: "222", title: "Justin Jackson" },
                { id: "223", title: "Reggie Jackson" },
                { id: "224", title: "LeBron James" },
                { id: "225", title: "DaQuan Jeffries" },
                { id: "226", title: "Ty Jerome" },
                { id: "227", title: "Amile Jefferson" },
                { id: "228", title: "James Johnson" },
                { id: "229", title: "Keldon Johnson" },
                { id: "230", title: "Stanley Johnson" },
                { id: "231", title: "Tyler Johnson" },
                { id: "232", title: "Nikola Jokic" },
                { id: "233", title: "Derrick Jones Jr." },
                { id: "234", title: "Tre Jones" },
                { id: "235", title: "Mason Jones" },
                { id: "236", title: "Tyus Jones" },
                { id: "237", title: "DeAndre Jordan" },
                { id: "238", title: "Cameron Jordan" },
                { id: "239", title: "Cameron Johnson" },
                { id: "240", title: "Chris Johnson" },
                { id: "241", title: "Dakota Johnson" },
                { id: "242", title: "James Johnson" },
                { id: "243", title: "Tyler Johnson" },  { id: "244", title: "Wesley Johnson" },  { id: "245", title: "Jalen Johnson" },  { id: "246", title: "Bones Hyland" },  { id: "247", title: "Jonathan Kuminga" },  { id: "248", title: "Luke Kornet" },  { id: "249", title: "Furkan Korkmaz" },  { id: "250", title: "Maxi Kleber" },  { id: "251", title: "Kevin Knox II" },  { id: "252", title: "Kyle Kuzma" },  { id: "253", title: "Rodions Kurucs" },  { id: "254", title: "Zach LaVine" },  { id: "255", title: "Skal Labissiere" },  { id: "256", title: "Jeremy Lamb" },  { id: "257", title: "Shane Larkin" },  { id: "258", title: "Nassir Little" },  { id: "259", title: "Kevon Looney" },  { id: "260", title: "Brook Lopez" },  { id: "261", title: "Robin Lopez" },  { id: "262", title: "Kevin Love" },  { id: "263", title: "Kyle Lowry" },  { id: "264", title: "Timothe Luwawu-Cabarrot" },  { id: "265", title: "Trey Lyles" },  { id: "266", title: "Frank Mason III" },  { id: "267", title: "Nico Mannion" },  { id: "268", title: "Terance Mann" },  { id: "269", title: "Boban Marjanovic" },  { id: "270", title: "Lauri Markkanen" },  { id: "271", title: "Caleb Martin" },  { id: "272", title: "Cody Martin" },  { id: "273", title: "Kelan Martin" },  { id: "274", title: "Kenyon Martin Jr." },  { id: "275", title: "Frank Mason III" },  { id: "276", title: "Thon Maker" },  { id: "277", title: "Makur Maker" },  { id: "278", title: "Jarell Martin" },  { id: "279", title: "Kelan Martin" },  { id: "280", title: "Khris Middleton" }



        ]}
      />
      <Text style={{ color: colors.background, fontSize: 13 }}>Selected item: {JSON.stringify(selectedItem)}</Text>
    </View>
  )
})

const styles = StyleSheet.create({
   container:{
    padding: 10,
    marginBottom: 20,
    backgroundColor: colors.textColor,
    borderRadius: 5,
    height: 50,
    width: 250, 
    
  },
  text: {
    color: colors.textColor,
    fontSize: 20,
    
  }

});